# Generated by Django 3.2.7 on 2021-09-13 20:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('green', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('blue', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('alpha', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255)])),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rgblent_api.color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
